%YAML:1.0
img_width: 1920
img_height: 1080
size_scale_factor: 1.
fx: 1.0741865278494929e+03
fy: 1.0752470419996366e+03
cx: 9.4718453472248825e+02
cy: 5.3970135723667124e+02
has_dist_coeff: 1
dist_px: -1.2659192676130165e-03
dist_py: -1.2629143897145197e-03
dist_k0: 9.6427877285232694e-02
dist_k1: -1.7112760524482026e-01
dist_k2: 8.4950451232046614e-02
dist_k3: 0.
dist_k4: 0.
dist_k5: 0.
term_epsilon: 9.9999999999999995e-08
